# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold fg:2) " # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[➜](bold red) "

[line_break]
disabled = true

# configure directory
[directory]
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "bold italic #87A752"
