
#theme = "dracula"
#theme = "gruvbox"
theme = "pop-dark"
#theme = "dark_plus"

[editor]
line-number = "relative"
mouse = false
middle-click-paste = true

[editor.whitespace]
render = "all"


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true
